### PR TITLE
[ADZ-595] OAS Schema field items

### PR DESCRIPTION
**Pull request by ziemsky**
Content of property `items` is now rendered
on API Specification page.

Also:
- Fix: numerical properties are now rendered
  when set to zero (see `NumberNotNullHelper`).
- `<div>` for `type` and `format` is now only
  rendered when at least one of the two is
  present.
- `properties` label and the containing row
  are no longer rendered.
- CSS was slightly optimised to improve
  readability of the schema content.

### CODE REVIEW

**Comment by ziemsky** [comment]
The latest commit ` e07fa36` has no functional changes compared to the original `66e1234` - it is only a rebase onto the latest `master`.

**Comment by ziemsky** [comment]
The latest commit `539d320` has no functional changes compared to the previous one `66e1234` - it is only a rebase onto latest commit on `master` branch.

**Review by monika10793 — APPROVED** [review]

**Comment by ziemsky** [comment]
Commit `20d9e0b` is a rebase onto master, with the addition of `--sticky-nav` in order to accomodate the necssary fix from DW-1557 to ensure that the nav menu remains 'sticky'.

Other than that there are no functional changes compared to the last approved commit - `539d320` on 2020-11-09.

**Comment by ziemsky** [comment]
Commit `8e1b77b` is a rebase onto latest `master`, with the addition of `--sticky-nav` in order to accommodate the necessary fix from DW-1557 to ensure that the side nav menu remains 'sticky'.

Other than that there are no functional changes compared to the last approved commit - `539d320` on 2020-11-09.

**Review by GeoffHayward — APPROVED** [review]

**Pull request merged**
